name: Full Stack CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend_setup:
    runs-on: ubuntu-20.04
    environment: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install backend dependencies
        run: npm install
        working-directory: ./backend
      - name: List environment variables for debugging
        run: printenv
        working-directory: ./backend
      - name: Start backend
        run: npm run start:test > backend.log 2>&1 &
        env:
          PORT: 3003
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        working-directory: ./backend

  frontend:
    runs-on: ubuntu-20.04
    needs: backend_setup
    environment: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install frontend dependencies
        run: npm install
        working-directory: ./frontend
      - name: Build frontend
        run: npm run build
        working-directory: ./frontend
      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          start: npm run start-prod
          wait-on: http://localhost:${{ env.PORT }}
          working-directory: ./frontend
