name: Full Stack CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend_setup:
    runs-on: ubuntu-20.04
    outputs:
      port: ${{ steps.find-port.outputs.port }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install backend dependencies
        run: npm install
        working-directory: ./backend
      - name: Start backend
        run: npm run start:test &
        working-directory: ./backend
      - name: Find port
        id: find-port
        run: echo "::set-output name=port::$(lsof -t -i:3000 -sTCP:LISTEN || echo 3000)"

  frontend:
    runs-on: ubuntu-20.04
    needs: backend_setup
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install frontend dependencies
        run: npm install
        working-directory: ./frontend
      - name: Build frontend
        run: npm run build
        working-directory: ./frontend
      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          start: npm run start:test
          wait-on: "http://localhost:${{ needs.backend_setup.outputs.port }}"
          working-directory: ./frontend
