name: Full Stack CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DEFAULT_PORT: 3000 # Default port if not provided by GitHub secrets or environment variables

jobs:
  backend_setup:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install backend dependencies
        run: npm install
        working-directory: ./backend
      - name: Start backend
        run: npm run start:test > /dev/null 2>&1 &
        working-directory: ./backend
      - name: Check backend availability
        run: |
          echo "Waiting for backend to be ready..."
          until curl --output /dev/null --silent --head --fail http://localhost:${{ env.DEFAULT_PORT }}; do
            printf '.'
            sleep 5
          done

  frontend:
    runs-on: ubuntu-20.04
    needs: backend_setup
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install frontend dependencies
        run: npm install
        working-directory: ./frontend
      - name: Build frontend
        run: npm run build
        working-directory: ./frontend
      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          start: npm run cypress:run
          wait-on: "http://localhost:${{ env.DEFAULT_PORT }}"
          working-directory: ./frontend
