name: Deployment Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      # Install backend dependencies
      - name: Install backend dependencies
        run: npm install
        working-directory: ./backend # Consistently use './backend' to avoid path issues

      # Run ESLint
      - name: Lint backend
        run: npm run lint
        working-directory: ./backend # Ensure we are in the correct directory

      # Run backend tests
      - name: Run backend tests
        run: npm run test
        working-directory: ./backend # Consistently use './backend'

      - name: List backend directory contents
        run: ls -alh
        working-directory: ./backend

  # setup_frontend:
  #   runs-on: ubuntu-20.04
  #   needs: setup_backend
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: "20"
  #     - name: Install frontend dependencies
  #       run: npm install
  #       working-directory: ./frontend

  # lint_frontend:
  #   runs-on: ubuntu-20.04
  #   needs: setup_frontend
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: "20"
  #     - name: Lint frontend
  #       run: npx eslint .
  #       working-directory: ./frontend

  # frontend_tests:
  #   runs-on: ubuntu-20.04
  #   needs: lint_frontend
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: "20"
  #     - name: Build the application
  #       run: npm run build
  #       working-directory: ./frontend
  #     - name: Start test server
  #       run: npm run start:test
  #       working-directory: ./frontend
  #     - name: Cypress E2E Tests
  #       uses: cypress-io/github-action@v6
  #       with:
  #         command: npm run cypress:run
  #         start: ""
  #         wait-on: http://localhost:5173
